### ISSUE TITLE
svgs not displaying in Chrome - mime type for *.svg files is incorrect

### ISSUE THREAD

**Issue by btakita** [lukeed/sirv#10]
It looks like Chrome requires the mime-type to be set to `image/svg+xml` to display the image.

`serve-static` does this correctly.

**Comment by lukeed** [comment]
Hey, thanks!

What's the mimetype it's adding instead? If you inspect the file content, is it correct?

I'm thinking that if the content is correct but the mime type isn't, then it's a discrepancy between `mime` and `mime/lite`.

Although, I don't think that's likely to be the case because I'm serving SVGs in my apps with appropriate mimes/visual behavior.

If content is empty, then you're probably looking for `--dev` mode

**Comment by btakita** [comment]
You're right. It looks like removing the `dev` flag fixes the issue.

I was seeing `<img>` & `background-image` not displaying the svg image.

**Comment by lukeed** [comment]
Oh wait, _adding_ the `--dev` flag causes the issue?

**Comment by lukeed** [comment]
Oh okay, I see the mistake. This is indeed a bug with dev mode. Will fix immediately.

Thanks!
