### ISSUE TITLE
Different Cache-Control value based on actual path being served

### ISSUE THREAD

**Issue by banjeremy** [lukeed/sirv#113]
Hello!

How do you feel about exposing the path of the file being served to the [`setHeaders` function](https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L176)?

My use case is that I'd like to send a different `Cache-Control` header depending on what is being served. 

E.g., my static assets live in a directory called `static` with a hash in their filenames. I would like to cache these indefinitely. Everything else (usually my `index.html` because I'm running in SPA mode) I don't want cached.

```ts
sirv('public', {
  single: true,
  setHeaders: function (res, pathname, stats, abs) {
    if (abs.includes('static')) {
      res.setHeader('Cache-Control', 'public,max-age=31536000,immutable');
    } else {
      res.setHeader('Cache-Control', 'no-cache');
    }
  },
});
```

I'm open to suggestions if you know a better way to accomplish this. 

Thanks!

**Comment by lukeed** [comment]
Hey,

Two (better, imo) alternatives:

1) React to the `pathname` since that's the access point anyway. Your `public/static/**` contents are being mapped to `/static/*` so might as well think of assets / treat them that way. Thinking in terms of URL access points means that your internal directory structure can move around without affecting the URL location.

2) Use multiple `sirv` instances – there's no performance penalty here. Since an entire partition of your `public` directory should behave differently, just split it up & provide different config:

```js
const statics = sirv('public/static', {
  maxage: 31536000,
  immutable: true,
})

// everything else
// You had `no-cache` so this is equivalent
// ~> altho it does touch filesystem
const assets = sirv('public', { 
  single: true, 
  dev: true,
})

// or use in-memory cache & set headers
const assets = sirv('public', {
  single: true,
  setHeaders(res) {
    res.setHeader('Cache-Control', 'no-cache');
  }
})
```

> **Note:** If _not_ using `dev: true` for the 2nd instance, you probably want to move `/public/static` into `/static` – or employ some other type of separation – so that you're not holding the same assets in-memory twice. 

Once you have those in place, it's just a matter of routing to the correct middleware function:

```js
function handler(req, res) {
  if (req.url.startsWith('/static')) {
    return statics(req, res);
  } else {
    return assets(req, res);
  }
}

// or with Polka/Express

polka()
  .use('/static', statics)
  .use(assets)
```

Hope that helps

**Comment by banjeremy** [comment]
Awesome! I didn't consider using multiple instances. I believe this will work. Thanks for your help!
