### ISSUE TITLE
Dynamic html files

### ISSUE THREAD

**Issue by jaclas** [lukeed/sirv#125]
I will use sirv when building an application in Svelte. I'm converting an old site written in PHP to Svelte/JS. I am using svelte-routing and would like the application to capture and process all addresses identically as it was in the old application. Unfortunately I encountered a problem, I will give a simplified example.

In the old application links were built like this:

/items/123_description.html   <-- .html on the end

When I call this address, unfortunately I get 404:

```
 [19:30:57] 200 ─ 1.42ms ─ /items/777_test   <--- ok
 [19:30:57] 200 ─ 1.43ms ─ /build/bundle.css
 [19:30:57] 200 ─ 5.19ms ─ /build/bundle.js
 [19:30:57] 200 ─ 3.94ms ─ /build/bundle.js.map
 [19:31:07] 404 ─ 0.09ms ─ /items/777_test.html <-- ERROR
```

Although in sirv settings I added --single:

>     "start": "sirv public --single --no-clear",

I am not sure where the cause is, but I can't solve it for several hours and I suspect in the way sirv works. 
I would like addresses with .html at the end to be routed well.

**Comment by lukeed** [comment]
The `/items/777_test` path is extensionless & applies some loose matching assumptions because of the `--single` flag, see [here](https://github.com/lukeed/sirv/tree/master/packages/sirv#optssingle) for more explanation on what those assumptions are.

When accessing a path that includes an extension (eg `/items/777_test.html`) then It's a request for that specific. If it does not exist then it correctly should 404
