### ISSUE TITLE
Keeping URL route whit SPA mode ?

### ISSUE THREAD

**Issue by liorchamla** [lukeed/sirv#24]
Hello to all of u, first of all, really nice feature and lightweight also !

I'm actually doing a little JS application which deals with routes (as /items, /items/:id etc). I found out sirv had a Single Page option, but the behavior seems weird.

If i go to http://myurl.loc/test, sirv will automaticly redirect me on http://myurl.loc/ 

Have u any suggestion to make him behave more like a Rewrite rule to index more than a redirect behavior ?

**Comment by lukeed** [comment]
Hey, sorry, I was out of town this weekend.

Are you using the `--single` flag? It does not _redirect_ – instead, it sends down the root directory's `index.html` file instead. Put differently, `curl http://myurl.loc` response will be the exact same markup as `http://myurl.loc/test` – assuming that `test.html` and `test/index.html` don't exist.

If you are seeing a **redirect** then your client-side router must be doing that. This is likely because the CSR doesn't recognize `/test` and redirects to your 404/error page... a lot of libraries will default to `/` as this 404/error/default page.

I'll be happy to continue looking at your code (if you share any), but this is not `sirv`'s doing. There is no redirect logic or behaviors anywhere in the code.

Closing because of this, but again, more than happy to continue looking & debugging with you! 😄 

Cheers~!

**Comment by paulocoghi** [comment]
I also reinforce that, technically, the problem must be on the client-side router.
