### ISSUE TITLE
Failed reloading Vue's nested routes

### ISSUE THREAD

**Issue by anonimusprogramus** [lukeed/sirv#36]
I followed [vue-router's nested routes](https://router.vuejs.org/guide/essentials/nested-routes.html).

I run `sirv start --cors --single` on the folder.

Clicking link-by-link worked.

Reloading `http://localhost:5000/user` worked.

Reloading `http://localhost:5000/user/123` failed.

But Sirv logged that failed request as `200`.

I wonder if this issue is related with Sirv.

Thanks Luke!

**Comment by lukeed** [comment]
Hey, how are you attaching your bundle files? What does that script tag look like in the HTML template?

**Comment by anonimusprogramus** [comment]
Sorry, couldn't make a fiddle, so I put them on [gist](https://gist.github.com/anonimusprogramus/f0b27cfbf90ebb1b6379657cc5e6ba30).

Please kindly check.

**Comment by anonimusprogramus** [comment]
Failed when reloading `http://localhost:5000/settings/emails`

**Comment by lukeed** [comment]
It's because you have `<script src="app.js"></script>`

You're allowing relative pathing to take place, which works fine when you're on `example.com/:level1` routes but will fail on any level deeper than that.

In your last example, the `app.js` is being looked for at `http://localhost:5000/settings/app.js`, which is wrong and so the application dies.

Change your script to `<script src="/app.js"></script>` and it will work, since it's an absolute path and will always resolve _from the root_ and not from where you currently are.

**Comment by lukeed** [comment]
Same as #33

**Comment by anonimusprogramus** [comment]
Oh man, awesome! Thanks a lot!

**Comment by lukeed** [comment]
Awesome, no problem, glad you got it!
