### ISSUE TITLE
Support for TLS?

### ISSUE THREAD

**Issue by aigr** [lukeed/sirv#41]
It doesn't seem like sirv has support for serving over TLS. Is this something you're considering to add? If not, do you know of an alternative that does?

In any case, thanks for the great product!

**Comment by paulocoghi** [comment]
It is on the roadmap: https://github.com/lukeed/sirv/issues/2

But Luke probably didn't have time yet to focus on this issue.

**Comment by lukeed** [comment]
Hey, I'm working on HTTP/2 in the `next` branch. It's not available on npm yet, but I should be able to tag a release this week now that [`route-manifest`](https://github.com/lukeed/route-manifest) is done.

You would have to setup a HTTP/2 server (which requires TLS for browser connections) since a HTTPS on its own would be pointless – the HTTP/2 will fallback to plain HTTPS over HTTP/1.1 if the client doesn't support HTTP/2 protocol.

**Comment by aigr** [comment]
Ok. :thumbsup:

**Comment by lukeed** [comment]
Now available, but still under the `@next` tag.

```
$ npm install sirv-cli@next
$ sirv public --http2 --key path/to/foo.pem --cert path/to/bar.pem --cacert optional
```

**Comment by AdrienGiboire** [comment]
Thanks! This seems to do the job! It took a long time to find this.
