### ISSUE TITLE
Several parameters with "public sirv --single"

### ISSUE THREAD

**Issue by elvticc** [lukeed/sirv#48]
Hello,

I'm using SvelteJS with "sirv public --single".

[http://localhost:5000/](http://localhost:5000/) works fine.

[http://localhost:5000/blog](http://localhost:5000/blog) works fine.

[http://localhost:5000/blog/1](http://localhost:5000/blog/1) works fine, only during a user action on the current page. If I modify the second parameter directly from the URL or if I click on a link from another website, the page goes blank and the error "_Uncaught SyntaxError: Unexpected token '<'_" is displayed in the console.

I do not have these problems with [http://localhost:5000/blog](http://localhost:5000/blog) for example.

Do you have a solution please?

**package.json**
```json
{
    "name": "svelte-app",
    "version": "1.0.0",
    "scripts": {
        "build": "npm install && rollup -c",
        "dev": "npm install && rollup -c -w",
        "build_sass": "npm run build && sass --style=compressed ./src/global.scss ./public/build/global.css",
        "dev_sass": "npm run dev & sass --style=compressed --watch ./src/global.scss ./public/build/global.css",
        "start": "sirv public --single"
    },
    "devDependencies": {
        "@rollup/plugin-node-resolve": "^7.1.1",
        "rollup": "^1.31.0",
        "rollup-plugin-commonjs": "^10.1.0",
        "rollup-plugin-livereload": "^1.0.4",
        "rollup-plugin-svelte": "^5.1.1",
        "rollup-plugin-terser": "^5.2.0",
        "sass": "^1.25.0",
        "svelte": "^3.18.2",
        "svelte-preprocess": "^3.4.0"
    },
    "dependencies": {
        "page": "^1.11.5",
        "sirv-cli": "^1.0.0-next.3"
    }
}
```

**routes.js**
```javascript
import Home from "./pages/Home.page.svelte";
import Blog from "./pages/Blog.page.svelte";
import NotFound from "./pages/NotFound.page.svelte";

export default [
    {
        path: "/",
        page: Home
    },
    {
        path: "/blog",
        page: Blog
    },
    {
        path: "/blog/:id",
        page: Blog
    },
    {
        path: "*",
        page: NotFound
    }
];
```

**App.svelte**
```html
<script>
    import router from "page";
    import routes from "./routes.js";

    let page;
    let params;

    // @see https://github.com/visionmedia/page.js
    // @see https://jackwhiting.co.uk/posts/setting-up-routing-in-svelte-with-pagejs/
    // @see https://jackwhiting.co.uk/posts/refactoring-our-router-within-svelte/
    // @see https://codesandbox.io/s/sveltepagejs-routing-example-pckm7
    routes.forEach(route => {
        router(
            route.path,

            (context, next) => {
                params = context.params;
                next();
            },

            () => {
                page = route.page;
            }
        );
    });

    router.start();
</script>

<header>
    <nav>
        <a href="/">Home</a>
        <a href="/blog">Blog</a>
        <a href="/blog/1">Article 1</a>
    </nav>
</header>

<main>
    <svelte:component this={page} params={params} />
</main>
```

**Blog.page.svelte**
```html
<script>
    export let params;

    console.log("Params:", params);
</script>

<h1>Blog page</h1>

{#if "id" in params}
    <p>Article {params.id}</p>
{/if}
```

**Comment by lukeed** [comment]
Hey there,

It's most definitely something to do with your App or your router config. Not sure & I don't have enough info or experience with `page` to know what's wrong based on what you've shown me.

Although I can confidently say it's nothing to do with `sirv` since this is a basic use case I rely on hundreds of times per day. You can look at my [`svelte-demo`](https://github.com/lukeed/svelte-demo) which uses the exact same `/blog` and `/blog:/id` routing structure you're after. It correctly works when you hard-reload on any article route.

Sorry I can't offer more help or insight for you, but hopefully that demo gives you enough of a lead!

**Comment by lukeed** [comment]
Oh! I reread your issue and this part stands out:

```
"Uncaught SyntaxError: Unexpected token '<'" 
```

This tells me you're seeing a JS error. 

What I bet is happening is your HTML/layout's assets aren't using absolute pathing. And so that's why your App works on any path that's only 1-level deep.

So, having something like `<script src="bundle.js">` will resolve to `/blog/bundle.js` when trying to load it from an Article route. You need to use `<script src="/bundle.js">` (and same for styles).

Please see https://github.com/lukeed/sirv/issues/33 and https://github.com/sveltejs/template/pull/46

**Comment by elvticc** [comment]
Thank you very much! You are amazing and so quick to answer 😁

**Comment by csellis** [comment]
Works for me as well. My issue was with Tailwind generated CSS. I was getting the structure of my HTML with no styles.

_public/index.html_
```
<link rel='icon' type='image/png' href='/favicon.png'>
<link rel="stylesheet" href="index.css" />    <----
<link rel='stylesheet' href='/build/bundle.css'>
```
to
```
<link rel='icon' type='image/png' href='/favicon.png'>
<link rel="stylesheet" href="/index.css" />    <----
<link rel='stylesheet' href='/build/bundle.css'>
```
