### ISSUE TITLE
Major version bump to 1.0

### ISSUE THREAD

**Issue by Siilwyn** [lukeed/sirv#57]
Please consider following semver, it doesn't mean the project is suddenly 'done' or has changed. It just gives users context about the change and reliability that patch and minor changes won't break their code base.

As Stephan Bönnemann (who is arguing hard for semver and did talks on the subject), loosely quoted:
> Version numbers should be used to avoid dependency hell... There's no reason for keeping the version number low, expect for marketing or maybe emotional attachment to versions. There's this concept in our mind that the version number has something to say about the project or the process or the stability and all of this is wrong... People believe something incredible existing is happening when a major/breaking version is released...

Please consider this.

**Comment by lukeed** [comment]
Hi there,

Why are you posting this? Is something wrong?

The next version _will be_ 1.0 – that's why development has been sitting behind the `next` branch/tag.

**Comment by lukeed** [comment]
Closing, since this is of course the game plan. Every one of my packages respects semver.

Also, FWIW, in any pre-1.0 semver project, minor versions represent new features and/or breaking changes. Semver clients (eg, npm) respect and abide by this rule too; so `^0.3.1` will only auto-update to any 0.3.x version, where as `^1.3.0` will auto-update to any 1.x.x version.
