### ISSUE TITLE
Sync glob performance?

### ISSUE THREAD

**Issue by crazy4groovy** [lukeed/sirv#6]
Hi - I noticed you're using `require('tiny-glob/sync')` -- are there any performance implications for using sync with high-quantity connections, versus async/promise?

**Comment by lukeed** [comment]
Hey~!

Yeah, the `sync` version [_is_ slower](https://github.com/terkelg/tiny-glob/pull/10) than the main async copy, but I'm using it intentionally for a few reasons:

1) The glob expansion is only performed **once**, at start-up
2) I want/need to support Node 6 since it's still in LTS maintenance
3) Middleware are rarely/never asynchronously booted

Using the `async` version of `tiny-glob` would force users to wrap their server start-ups in an async wrapper, just so that they could await the middleware -- super super strange.

**Comment by crazy4groovy** [comment]
Ah, I read it too quickly and didn't realize this was a start-up process. Sounds reasonable!
