### ISSUE TITLE
Question about how to newly added resource

### ISSUE THREAD

**Issue by biaocy** [lukeed/sirv#72]
Hi, thank you for creating this wonderful project.

I'm using `sirv` with `sapper` to serve some static images. And these images can be uploaded through back-end. Then these images will be relocated to `sirv`'s `dir`.

Because `sirv` will only [scan file-system once](https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L135) when it's imported, these newly added images will not exists in cache, so you get 404 when visit these images in browser.

So my question is, can we add some logic, like lookup file-system when resource not found, to handle newly added resource?

**Comment by biaocy** [comment]
After second look, I found option [onNoMatch](https://github.com/lukeed/sirv/tree/master/packages/sirv#optsonnomatch). So, we can lookup file-system in here when resource not found. But we are unable to update the cache here. 

Is it wise to expose cache to `onNoMatch`, so we can update it?

**Comment by lukeed** [comment]
Hey, than you :)

There's no way to expose/update the cache post-startup. This is intentional.
What I would recommend doing is organizing your assets in such a way that _your_ assets (the website's) are in one location, and the dynamic, user-uploaded images are somewhere else.

Then you would run two instances of `sirv` -- a "dev" variant for the user images (since theyre transient) and "prod" for your own.

> PS: You also would not want a never-ending supply of images being added to your internal cache. That would cause high memory usage very very quickly.

The final snippet would roughly look something like this:

```js
sirv('public/static'); //~> cache instance on your own assets
sirv('public/uploads', { dev: true }); // -> fs reads on dynamic asset supply
```

Hope that helps!

**Comment by monkape** [comment]
Sorry to resurrect this, but using `dev` totally defeats the purpose of this package, even the readme says

> The massive performance advantage over serve-static is explained by not relying on the file system for existence checks on every request. These are expensive interactions and must be avoided whenever possible!

> Important: Do not use dev mode in production!

Why not check the file system only for requests not found in the cache - then cache them if found? That would make the "expensive interactions" fire only the first time a file is requested and for nonexistent files (which shouldn't be requested in normal app usage anyway).

**Comment by lukeed** [comment]
Because then the first request for every asset is significantly slower, ruining short-lived invocations like serverless. It's much cheaper & faster to traverse the fs upfront than to restart on every request, only to save the results.

Plus it's important to have a clear delineation between "hold X in memory, but don't hold Y". TBH, I meant to rename the "dev" option to "cache" during the 1.0 pass because there are valid use cases for `dev`. The README notes are just to draw attention to the fact that there _is_ an internal cache and 95% of the time, apps should be using it.

Continuing my `public/uploads` example – what if these were user-uploaded videos? There is absolutely zero reason to store this in RAM as they may be accessed very infrequently & can be quite large – especially if there's a few of them. Or, similarly, a user uploads an image, and `public/uploads` is just a preview/temporary destination. In both cases, you do not want to waste your memory on these assets. This makes "dev" (wrongly named) the correct choice.

**Comment by monkape** [comment]
I understand your reasoning, however I was suggesting to populate the cache upfront and extend it with new content as it's requested. I think it's a common use case and thought it would be nice for the package to support it.

I appreciate your minimalistic performance-oriented approach (not just to this package) and have no problems implementing this myself for my needs.

**Comment by lukeed** [comment]
Thanks. Feel free to open an issue/RFC and it can collect feedback. Please include any relevant API/option suggestions for how it might be done, because at this point I can't imagine a non-confusing way to distinguish between "just what's here", "use file system", and "do both". 

It might be worth considering for a 2.0 at some point – at which time I'll also be sure to rename the option.

**Comment by PlopTheReal** [comment]
behing able to hot update the cache would be very nice.
