### ISSUE TITLE
How to use path prefix with sirv?

### ISSUE THREAD

**Issue by fusionstrings** [lukeed/sirv#9]
Thanks for great work. I am trying to use sirv with Polka and Sapper.

I have my public assets in folder 'public' and I want to reference those assets with path prefix say `public/images/hero.jpg`.

When I use Sirv as `app.use(sirv('public'))`, I need to refer static assets as `images/hero.jpg`.
I am basically looking for something like `app.use('/static', express.static(path.join(__dirname, 'public')))`.

**Comment by lukeed** [comment]
Hey, thanks~!

The current combination of Polka & Sapper doesn't really allow for this right now, unless you do this:

```js
// create the middleware early
//~> so that you don't recreate every time
const assets = sirv('public');

polka()
  .use(
    compression(),
    // ...
    (req, res, next) => {
      // check if we're looking at a /static/* request
      return req.path.startsWith('/static/') ? assets(req, res, next) : next();
    },
    // ...
    sapper({ manifest })
  )
```

A few others have had this request a few times, so I've opened a PR (https://github.com/sveltejs/sapper/pull/326) on Sapper to make this easier for Polka users. Hopefully it aligns with their goals, otherwise the above will do the trick for you :)

Without Sapper, using `sirv` with Polka operates as you'd expect:

```js
polka()
  .use('/static', sirv('public'))
  // ...
```

**Comment by fusionstrings** [comment]
Thanks for very quick response and clarification.

**Comment by lukeed** [comment]
No problem, hope it helped!

**Comment by fusionstrings** [comment]
Yes, the sirv API you mentioned `polka().use('/static', sirv('public'))`, worked.
I couldn't get it working with sapper though. (which is irrelevant to sirv) ;)

**Comment by lukeed** [comment]
The 1st snippet I provided didn't do the trick?

**Comment by fusionstrings** [comment]
Not really but can be something from my side. I'll give it another try share the repo. It's a little embarrassing, I am slow and you are proactive in helping me.

**Comment by lukeed** [comment]
Lol okay, no worries. Whenever you get a chance I'll take a look 👍

**Comment by lukeed** [comment]
Thanks for the kind words, but not a problem! I'm familiar with all the libraries involved (and am responsible for two of them) so I'm happy to help.

I made a mistake, here's what you need to do:

```diff
// app/server.js

(req, res, next) => {
-  // check if we're looking at a /static/* request
-  return req.path.startsWith('/assets/') ? assets(req, res, next) : next();
+  if (req.path.startsWith('/assets/')) {
+    req.path = req.path.substring(7); // remove "/assets" prefix
+    assets(req, res, next);
+  } else {
+    next();
+  }
},
```

This takes care of the runtime / server requests. 

However, your service worker (scaffolded by default from Sapper) will be incorrect since you want your assets to be prefixed with `/assets` &mdash; you will have to update those directly.

```diff
// app/manifest/service-worker.js

export const assets = [
-  "favicon.png",
-  "global.css",
-  "great-success.png",
-  "manifest.json",
-  "svelte-logo-192.png",
-  "svelte-logo-512.png"
+  "assets/favicon.png",
+  "assets/global.css",
+  "assets/great-success.png",
+  "assets/manifest.json",
+  "assets/svelte-logo-192.png",
+  "assets/svelte-logo-512.png"
];
```

**Comment by fusionstrings** [comment]
GREAT SUCCESS! 💯 

You are awesome. I can't thank you enough. More than the solution I am grateful for goodwill. This has been very inspiring.

**Comment by lukeed** [comment]
GREAT SUCCESS! HIGH FIVE 😂😂
